name: Build and Release

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a tag starting with "v"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Get dependencies
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake zip libcurl4-openssl-dev nlohmann-json3-dev

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          choco install cmake -y
          choco install zip -y
          choco install mingw -y

          curl -L -o curl-win64.zip "https://curl.se/windows/latest.cgi?p=win64-mingw.zip"
          unzip curl-win64.zip -d curl-win64
          # Copy curl libraries and includes to a known location
          mkdir -p packages/curl
          cp -r curl-win64/*/bin packages/curl/
          cp -r curl-win64/*/lib packages/curl/
          cp -r curl-win64/*/include packages/curl/

          echo "${GITHUB_WORKSPACE}/packages/curl/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/packages/curl/lib" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/packages/curl/include" >> $GITHUB_PATH


      # Build Linux
      - name: Build
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Move and zip built files for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cd build/bin
          zip -j app-${{ matrix.os }}.zip *

      - name: Move and zip built files for Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          cp build/lib/libspdlog.so.1.15 build/bin/libspdlog.so.1.15
          cd build/bin
          zip -r app-${{ matrix.os }}.zip *

      # Upload build artifacts
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: build/bin/app*.zip
          if-no-files-found: error

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
