name: Build and Release

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a tag starting with "v"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Linux build
      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make zip
          make
          mv ./app ./app-${{ matrix.os }}
          zip -r app-${{ matrix.os }}.zip app-${{ matrix.os }} SteamAPI/linux64/libsteam_api.so

      # Windows build
      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          g++ -g $(find ./src -name '*.cpp') \
            -o ./app-${{ matrix.os }}.exe \
            -I. \
            -L./SteamAPI/win64 -lsteam_api64 \
            -Wl,-rpath,'$ORIGIN/SteamAPI/win64' \
            -static-libgcc -static-libstdc++ -static \
            -pthread
        # Create zip using PowerShell
      - name: Zip Windows build
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path app-${{ matrix.os }}.exe, SteamAPI/win64/steam_api64.dll -DestinationPath app-${{ matrix.os }}.zip

      # Upload build artifacts
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: app*.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
