name: Build and Release

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a tag starting with "v"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Setup vcpkg
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'master'

      # Get dependencies
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake ninja-build zip

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          choco install cmake -y
          choco install ninja -y
          choco install zip -y
          choco install mingw -y

      # Build
      - name: Build
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
          cmake --build build


      # Move and zip built files
      - name: Move and zip built files for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cd build/bin
          zip -j app-${{ matrix.os }}.zip *

      - name: Move and zip built files for Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          cp build/lib/libspdlog.so.1.15 build/bin/libspdlog.so.1.15
          cd build/bin
          zip -r app-${{ matrix.os }}.zip *

      # Upload build artifacts
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: build/bin/app*.zip
          if-no-files-found: error

      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
