name: Build and Release

on:
  push:
    tags:
      - "v*"   # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Build on Linux
      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make
          make
          mv ./app ./app-linux

      # Build on Windows
      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          g++ -g $(find ./src -name '*.cpp') \
            -o ./app-windows.exe \
            -I. \
            -L./SteamAPI/win64 -lsteam_api \
            -pthread

      # Upload artifact for each OS
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            app-linux
            app-windows.exe
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
