name: Build and Release

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a tag starting with "v"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Linux build
      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make
          make
          mv ./app ./app-${{ matrix.os }}

      # Windows build
      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          # Set up MSVC environment
          Import-Module "$env:VSCMD_INSTALLATION_PATH/Common7/Tools/Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $env:VSCMD_INSTALLATION_PATH -Arch amd64
          # Compile all .cpp files with MSVC
          cl /EHsc /std:c++17 /I. /I./SteamAPI/win64 /Feapp-${{ matrix.os }}.exe src\*.cpp /link /LIBPATH:./SteamAPI/win64 steam_api64.lib

      # Upload build artifacts
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: app*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
